### ISSUE TITLE
Missing styling of inner element (textarea or input) of SuggestionsInput

### ISSUE THREAD

**Issue by jdb78** [plotly/dash-extra-components#10]
The SuggestionsInput cannot be styled properly, e.g.
`SuggestionsInput(style=dict(width='100%'))` has not effect on the underlying textarea or input. I believe this can be fixed by propagating down `className` and `style` to the textarea or input.

This should happen here:
https://github.com/plotly/dash-extra-components/blob/master/src/lib/components/SuggestionsInput.react.js#L386

**Comment by T4rk1n** [comment]
Right it gives them to the wrapper div.
